Fix CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,13 +21,13 @@ jobs:
     # only run jobs via scheduled workflow in main repo, not in forks
     if: (github.event_name == 'schedule' && github.repository == 'uniolweb/uniolbeuser') || (github.event_name != 'schedule')
     name: "static"
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     strategy:
       # This prevents cancellation of matrix job runs, if one/two already failed and let the
       # rest matrix jobs be be executed anyway.
       fail-fast: true
       matrix:
-        php: [ '8.4' ]
+        php: [ '8.3' ]
         minMax: [ 'composerInstallMax' ]
     steps:
       - name: "Checkout"
@@ -64,13 +64,13 @@ jobs:
     # only run jobs via scheduled workflow in main repo, not in forks
     if: (github.event_name == 'schedule' && github.repository == 'uniolweb/uniolbeuser') || (github.event_name != 'schedule')
     name: "all core-latest"
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     strategy:
       # This prevents cancellation of matrix job runs, if one/two already failed and let the
       # rest matrix jobs be be executed anyway.
       fail-fast: true
       matrix:
-        php: [ '8.1', '8.2', '8.3' '8.4' ]
+        php: [ '8.1', '8.2', '8.3' ]
         minMax: [ 'composerInstallMax' ]
     steps:
       - name: "Checkout"
@@ -113,43 +113,43 @@ jobs:
 
   # v12 (enable this job when v13 is supported)
   # DISABLED
-  all_core_v12:
-    # only run jobs via scheduled workflow in main repo, not in forks
-    #if: (github.event_name == 'schedule' && github.repository == 'uniolweb/uniolbeuser') || (github.event_name != 'schedule')
-    if: false
-    name: "all core-v12"
-    runs-on: ubuntu-20.04
-    strategy:
-      # This prevents cancellation of matrix job runs, if one/two already failed and let the
-      # rest matrix jobs be be executed anyway.
-      fail-fast: true
-      matrix:
-        php: [ '8.1', '8.2', '8.3', '8.4' ]
-        minMax: [ 'composerInstallMax' ]
-    steps:
-      - name: "Checkout"
-        uses: actions/checkout@v2
-
-      - name: "show php version"
-        run: php --version
-
-      - name: "Set Typo3 core version"
-        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t "^12.4" -s composerCoreVersion
-
-      - name: "Add prophecy for unit / functional tests"
-        run: composer require --dev jangregor/phpstan-prophecy phpspec/prophecy phpspec/prophecy-phpunit typo3/testing-framework:^7
-
-      - name: "Composer"
-        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s ${{ matrix.minMax }}
-
-      - name: "phpstan"
-        if: ${{ always() && matrix.minMax == 'composerInstallMax' }}
-        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan -e "--error-format=github" -v
-
-      - name: "Unit tests"
-        if: always()
-        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit -v
-
-      - name: "Functional tests with mariadb"
-        if: always()
-        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional -v
+  #all_core_v12:
+  #  # only run jobs via scheduled workflow in main repo, not in forks
+  #  #if: (github.event_name == 'schedule' && github.repository == 'uniolweb/uniolbeuser') || (github.event_name != 'schedule')
+  #  if: false
+  #  name: "all core-v12"
+  #  runs-on: ubuntu-20.04
+  #  strategy:
+  #    # This prevents cancellation of matrix job runs, if one/two already failed and let the
+  #    # rest matrix jobs be be executed anyway.
+  #    fail-fast: true
+  #    matrix:
+  #      php: [ '8.1', '8.2', '8.3' ]
+  #      minMax: [ 'composerInstallMax' ]
+  #  steps:
+  #    - name: "Checkout"
+  #      uses: actions/checkout@v2
+  #
+  #    - name: "show php version"
+  #      run: php --version
+  #
+  #    - name: "Set Typo3 core version"
+  #      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t "^12.4" -s composerCoreVersion
+  #
+  #    - name: "Add prophecy for unit / functional tests"
+  #      run: composer require --dev jangregor/phpstan-prophecy phpspec/prophecy phpspec/prophecy-phpunit typo3/testing-framework:^7
+  #
+  #    - name: "Composer"
+  #      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s ${{ matrix.minMax }}
+  #
+  #    - name: "phpstan"
+  #      if: ${{ always() && matrix.minMax == 'composerInstallMax' }}
+  #      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s phpstan -e "--error-format=github" -v
+  #
+  #    - name: "Unit tests"
+  #      if: always()
+  #      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit -v
+  #
+  #    - name: "Functional tests with mariadb"
+  #      if: always()
+  #      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -d mariadb -s functional -v
